server {
    listen 80;
    server_name movo.kz www.movo.kz;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name movo.kz www.movo.kz;

    ssl_certificate /etc/letsencrypt/live/movo.kz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/movo.kz/privkey.pem;

    client_max_body_size 100M;

    location /api/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}