export const API_PATHS = {
  locations: "/locations",
  tourPhotos: "/tours/photos",
  tours: "/tours",
  tourById: (tourId: string) => `/tours/${tourId}`,
  signIn: "/suppliers/sign-in",
  filters: "/tours/filters",
  supplierMe: "/suppliers/me",
  supplierTourCounts: "/tours/supplier-tours/counts",
  supplierTours: "/tours/supplier-tours",
  uploadSupplierProfilePhoto: "/suppliers/profile-photo",
  deleteSupplierProfilePhoto: (photoId: string) => `/suppliers/profile-photo/${photoId}`,
  updateSupplierProfileInfo: "/suppliers/profile",
  deleteTour: (tourId: string) => `/tours/${tourId}`,
} as const
