export const API_PATHS = {
  locations: "/locations",
  tourPhotos: "/tours/photos",
  tours: "/tours",
  tourById: (tourId: string) => `/tours/${tourId}` as const,
  signIn: "/suppliers/sign-in",
  signUp: "/suppliers/sign-up",
  filters: "/tours/filters",
  supplierMe: "/suppliers/me",
  supplierTourCounts: "/tours/supplier-tours/counts",
  supplierTours: "/tours/supplier-tours",
  supplierTourReservations: "/tours/reservations",
  uploadSupplierProfilePhoto: "/suppliers/profile-photo",
  deleteSupplierProfilePhoto: (photoId: string) => `/suppliers/profile-photo/${photoId}` as const,
  updateSupplierProfileInfo: "/suppliers/profile",
  deleteTour: (tourId: string) => `/tours/${tourId}` as const,
  bookTour: `/tours/book`,
} as const
