import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { MainLayout } from "@/features/layouts/main-layout";
import { Provider } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={"antialiased bg-back-base"}>
        <AntdRegistry>
          <Provider>
            <MainLayout>{children}</MainLayout>
          </Provider>
        </AntdRegistry>
      </body>
    </html>
  );
}
